endiosGmbH/Android-Config

maven.gradle

https://endios.atlassian.net/browse/OP-2438

OP-2438 Move endios maven server

---

version.gradle

**Ticket:** [OP-2333](https://endios.atlassian.net/browse/OP-2333 "Link to JIRA")
- Upgrade android api levels for compile and target configuration
- all the consumers (dependent widgets) to test this build configuration

OP-2333 - Upgrade android api levels for compile and target configuration

---

version.gradle

**Ticket:** [OP-2483](https://endios.atlassian.net/browse/OP-2483 "Link to JIRA")
Upgrade Foundation module to release version
N/A

OP-2483 - Upgrade Foundation module to release version

---

version.gradle

**Ticket:** [OP-2483](https://endios.atlassian.net/browse/OP-2483 "Link to JIRA")
- Align google material gradle dependency version
N/A

OP-2483 - Align google material gradle dependency version

---

lib.gradle
tooling/.maven/maven_publish.gradle

**Ticket:** [OP-2311](https://endios.atlassian.net/browse/OP-2311 "Link to JIRA")
- Align maven artifact packaging with existing implementation
N/A

OP-2311 - Align maven artifact packaging with existing implementation

---

lib.gradle
tooling/.maven/maven_publish.gradle
version.gradle

**Ticket:** [OP-2311](https://endios.atlassian.net/browse/OP-2311 "Link to JIRA")
- Migrate maven artifact packaging gradle dependency and boot-strap gradle scripts
N/A

OP-2311 - Migrate maven artifact packaging gradle dependency and boot-strap gradle scripts

---

.github/pull_request_template.md
version.gradle

**Ticket:** [OP-2284](https://endios.atlassian.net/browse/OP-2284 "Link to JIRA")
- Add GitHub Pull Request Template
N/A

OP-2284 - Update Foundation module version

---

lib_ui_tests.gradle

**Ticket:** [PA-5](https://endios.atlassian.net/browse/PA-5 "Link to JIRA")
- Add custom packaging options for UI test build cruncher
N/A
N/A

PA-5 - Add custom packaging options for UI test build cruncher

---

version.gradle

**Ticket:** [OP-2421](https://endios.atlassian.net/browse/OP-2421)

OP-2421 image scaling when opened the first time

---

version.gradle

**Ticket:** [OP-2618](https://endios.atlassian.net/browse/OP-2618 "Link to JIRA")
N/A
N/A

OP-2618 - Update Foundation module version

---

version.gradle

**Ticket:** [OP-2603](https://endios.atlassian.net/browse/OP-2603 "Link to JIRA")
N/A
N/A

OP-2603 - Update Foundation module version

---

version.gradle

**Ticket:** [OP-2844](https://endios.atlassian.net/browse/OP-2844 "Link to JIRA")
N/A
N/A

OP-2844 - Update Foundation module version

---

version.gradle

**Ticket:** [OP-2653](https://endios.atlassian.net/browse/OP-2653)
**Purpose of this Pull Request:** Increase foundation  version

OP-2653  Bottom sheet pictures out of the background borders

---

version.gradle

**Ticket:** [OP-2899](https://endios.atlassian.net/browse/OP-2899)

OP-2899 [OneFilterBottomSheet ] Add possibility to change filters data

---

version.gradle

**Ticket:** [OP-2900](https://endios.atlassian.net/browse/OP-2900)

OP-2900 [OneInfoVIew] Extend view by additional button

---

version.gradle

**Ticket:** [OP-2668](https://endios.atlassian.net/browse/OP-2668)

OP-2668  All android apps: headline is cut off

---

version.gradle

**Ticket:** [OP-2834](https://endios.atlassian.net/browse/OP-2834)

OP-2834  Trier (äppes) App Android: Contact buttons (navigation, telephone, e-mail) are not displayed properly

---

version.gradle

**Ticket:** [OP-2708](https://endios.atlassian.net/browse/OP-2708 "Link to JIRA")
N/A
N/A

OP-2708 - Update Foundation module version

---

version.gradle

**Ticket:** [PA-103](https://endios.atlassian.net/browse/PA-103 "Link to JIRA")
- Align barcode generation dependency with existing usage
N/A
N/A

PA-103 - Align barcode generation dependency with existing usage

---

version.gradle

**Ticket:** [TICKET_ID](https://endios.atlassian.net/browse/OP-3041)

OP-3041 FilterBottomSheet. Update master filter logic

---

version.gradle

**Ticket:** [OP-3130](https://endios.atlassian.net/browse/OP-3130 "Link to JIRA")
N/A
N/A

OP-3130 - Update Foundation module version

---

version.gradle

**Ticket:** [OP-3034](https://endios.atlassian.net/browse/OP-3034 "Link to JIRA")
N/A
N/A

OP-3034 - Update Foundation module version

---

version.gradle

**Ticket:** [OP-3035](https://endios.atlassian.net/browse/OP-3035 "Link to JIRA")
N/A
N/A

OP-3035 - Update Foundation module version

---

version.gradle

**Ticket:** [OP-3213](https://endios.atlassian.net/browse/OP-3213 "Link to JIRA")
N/A
N/A

OP-3213 - Update Foundation module version

---

version.gradle

**Ticket:** [OP-3180](https://endios.atlassian.net/browse/OP-3180 "Link to JIRA")
N/A
N/A

OP-3180 - Update Foundation module version

---

version.gradle

**Ticket:** [OP-2943](https://endios.atlassian.net/browse/OP-2943)

OP-2943 CSS: MR 2.1 : Implausible View (Android)

---

version.gradle

**Ticket:** [OP-3689](https://endios.atlassian.net/browse/OP-3689)

OP-3689 [android] Implement deeplink logic

---

version.gradle

**Ticket:** [OP-3801](https://endios.atlassian.net/browse/OP-3801)

OP-3801 TimePicker crashes with IndexOutOfBoundsException

---

version.gradle

**Ticket:** [OP-3820](https://endios.atlassian.net/browse/OP-3820)

OP-3820 Add info button to OneBottomDialog

---

version.gradle

**Ticket:** [OP-3764](https://endios.atlassian.net/browse/OP-3764)

OP-3764 [Android] change colors of pins in maps clusters.

---

version.gradle

**Ticket:** [OP-2585](https://endios.atlassian.net/browse/OP-2585)

OP-2585 OneWidgetLinkService add possibility to open url links without HTTP/HTTPS prefix

---

version.gradle

**Ticket:** [OP-3755](https://endios.atlassian.net/browse/OP-3755)

OP-3755 mein Heidelberg: Navigation not working in content (Android)

---

version.gradle

**Ticket:** [PA-235](https://endios.atlassian.net/browse/PA-235)

PA-235 [android] Minutes can only be selected in the multiple of 5

---

version.gradle

**Ticket:** [OP-3632](https://endios.atlassian.net/browse/OP-3632 "Link to JIRA")
- increment foundation version

OP-3632 - increment foundation version

---

version.gradle

**Ticket:** [3831](https://endios.atlassian.net/browse/OP-3831 "Link to JIRA")

OP-3831 - updated foundation version

---

version.gradle

**Ticket:** [PA-261](https://endios.atlassian.net/browse/PA-261 "Link to JIRA")
* update foundation version

PA-261 - update foundation version

---

version.gradle

**Ticket:** [OP-3605](https://endios.atlassian.net/browse/OP-3605)
Enabled custom text for navigation button.

OP-3605: Enabled custom text for navigation button.

---

version.gradle

**Ticket:** [OP-2274](https://endios.atlassian.net/browse/OP-2274 "Link to JIRA")

OP-2274 - updated foundation version

---

version.gradle

**Ticket:** [OP-3605](https://endios.atlassian.net/browse/OP-3605)
Fixed Navigation button custom text declaration.

OP-3605: Fixed Navigation button custom text declaration.

---

version.gradle

**Ticket:** [OP-3659](https://endios.atlassian.net/browse/OP-3659 "Link to JIRA")

OP-3659 - updated foundation version

---

version.gradle

**Ticket:** [OP-3755](https://endios.atlassian.net/browse/OP-3755 "Link to JIRA")

OP-3755 - updated foundation version

---

version.gradle

**Ticket:** [OP-3561](https://endios.atlassian.net/browse/OP-3561 "Link to JIRA")

fix/OP-5631 - updated foundation version

---

version.gradle

**Ticket:** [OP-4157](https://endios.atlassian.net/browse/OP-4157 "Link to JIRA")

fix/OP-4157 - updated foundation version

---

version.gradle

**Ticket:** [OP-3932](https://endios.atlassian.net/browse/OP-3932 "Link to JIRA")

feature/OP-3932 - updated foundation version

---

version.gradle

**Ticket:** [OP-3932](https://endios.atlassian.net/browse/OP-3932 "Link to JIRA")

OP-3932 - updated foundation version

---

version.gradle

**Ticket**: [OP-3663](https://endios.atlassian.net/browse/OP-3663)
**Ticket**: [OP-3672](https://endios.atlassian.net/browse/OP-3672)

OP-3663-3672 - updated foundation version

---

version.gradle

**Ticket:** [OP-4191](https://endios.atlassian.net/browse/OP-4191)

OP-4191 Android: PDF: pdf is not shown in full size and controls like iOS are missing

---

version.gradle

**Ticket:** [OP-4446](https://endios.atlassian.net/browse/OP-4446)

OP-4446 [Android] Autofill login fields from saved data

---

version.gradle

**Ticket:** [OP-4598](https://endios.atlassian.net/browse/OP-4598)

OP-4598 [Android] Map element should have a similar color to the design one

---

version.gradle

**Ticket:** [OP-4553](https://endios.atlassian.net/browse/OP-4553)

OP-4553 [Android] Events map bottom view is broken

---

version.gradle

**Ticket:** [OP-4630](https://endios.atlassian.net/browse/OP-4630)

OP-4630 DetailActivity is crashing when layout is overwritten

---

version.gradle

**Ticket:** [FTP-1](https://endios.atlassian.net/browse/FTP-1)

FTP-1 Use `viewBinding` in all widgets instead of synthetics

---

version.gradle

**Ticket:** [OP-4645](https://endios.atlassian.net/browse/OP-4645 "Link to JIRA")

OP-4645 - updated foundation version

---

version.gradle

**Ticket:** [OP-4723](https://endios.atlassian.net/browse/OP-4723)

OP-4723 WVV: Overlay is not displaying line breaks on Android

---

version.gradle

**Ticket:** [OP-4342](https://endios.atlassian.net/browse/OP-4342)

OP-4342 All (Löwenbündel App): Image in Overlay is not displayed

---

version.gradle

**Ticket:** [OP-4240](https://endios.atlassian.net/browse/OP-4240 "Link to JIRA")

OP-4240 - updated foundation version

---

version.gradle

**Ticket:** [OP-4533](https://endios.atlassian.net/browse/OP-4533)

OP-4533 Android: Add progress bar when playing a video

---

version.gradle

**Ticket:** [OP-4849](https://endios.atlassian.net/browse/OP-4849 "Link to JIRA")
updated permissions dispatcher library

OP-4849 - updated permissions dispatcher library

---

version.gradle

**Ticket:** [OP-4891](https://endios.atlassian.net/browse/OP-4891 "Link to JIRA")

OP-4891 - updated foundation version

---

version.gradle

**Ticket:** [OP-4720](https://endios.atlassian.net/browse/OP-4720)

OP-4720 Provide hook for widgets to deactivate background services

---

version.gradle

**Ticket:** [OP-4947](https://endios.atlassian.net/browse/OP-4947)

OP-4947 [Android] CSS Widgets: Deeplink to other CSS Widgets

---

version.gradle

**Ticket:** [OP-3788](https://endios.atlassian.net/browse/OP-3788 "Link to JIRA")

OP-3788 - updated foundation version

---

version.gradle

**Ticket:** [OP-5044](https://endios.atlassian.net/browse/OP-5044)

OP-5044 [android][swk] registration failure returns a white screen

---

version.gradle

**Ticket:** [OP-5146](https://endios.atlassian.net/browse/OP-5146 "Link to JIRA")

OP-5146 - updated foundation version

---

version.gradle

**Ticket:** [OP-5204](https://endios.atlassian.net/browse/OP-5204 "Link to JIRA")

OP-5204 - updated foundation version

---

version.gradle

**Ticket:** [OP-5256](https://endios.atlassian.net/browse/OP-5256 "Link to JIRA")

OP-5256 - updated foundation version

---

version.gradle

**Ticket:** [OP-5190](https://endios.atlassian.net/browse/OP-5190 "Link to JIRA")

OP-5190 - updated foundation version

---

version.gradle

**Ticket:** [OP-5288](https://endios.atlassian.net/browse/OP-5288 "Link to JIRA")

OP-5288 - updated foundation version

---

version.gradle

**Ticket:** [OP-5513](https://endios.atlassian.net/browse/OP-5513 "Link to JIRA")

OP-5513 - updated foundation version

---

version.gradle

**Ticket:** [OP-5513](https://endios.atlassian.net/browse/OP-5513 "Link to JIRA")

OP-5513 - update foundation version

---

version.gradle

**Ticket:** [OP-5514](https://endios.atlassian.net/browse/OP-5514 "Link to JIRA")

OP-5514 - updated foundation version

---

version.gradle

**Ticket:** [OP-5509](https://endios.atlassian.net/browse/OP-5509 "Link to JIRA")

OP-5509 - updated foundation version

---

version.gradle

**Ticket:** [OP-5514](https://endios.atlassian.net/browse/OP-5514)

OP-5514 📌 [Android]: Foundation text of tile button is truncated

---

common.gradle
version.gradle

**Ticket:** [OP-5481](https://endios.atlassian.net/browse/OP-5481 "Link to JIRA")
**Ticket:** [OP-5482](https://endios.atlassian.net/browse/OP-5482 "Link to JIRA")

OP-5481 - updated foundation version

---

version.gradle

**Ticket:** [OP-5286](https://endios.atlassian.net/browse/OP-5286)
**Purpose of this Pull Request:** Increase foundation and material versions

OP-5286   [Android] [SWK] LogIn: A space is added to the LogIn Data when logging in using the auto complete function

---

version.gradle

**Ticket:** [OP-5482](https://endios.atlassian.net/browse/OP-5482 "Link to JIRA")

OP-5482 - updated foundation version

---

version.gradle

**Ticket:** [OP-5714](https://endios.atlassian.net/browse/OP-5714 "Link to JIRA")

OP-5714 - updated foundation version

---

version.gradle

**Ticket:** [OP-3754](https://endios.atlassian.net/browse/OP-3754 "Link to JIRA")
updated foundation version 

OP-3754 - updated foundation version

---

version.gradle

**Ticket:** [OP-4170](https://endios.atlassian.net/browse/OP-4170 "Link to JIRA")

OP-4170 - updated foundation version

---

version.gradle

**Ticket:** [AGENCY-3644](https://endios.atlassian.net/browse/AGENCY-3644 "Link to JIRA")

AGENCY-3644 - updated foundation version

---

version.gradle

**Ticket:** [OP-5739](https://endios.atlassian.net/browse/OP-5739 "Link to JIRA")

OP-5739 - updated foundation version

---

version.gradle

**Ticket:** [OP-5753](https://endios.atlassian.net/browse/OP-5753 "Link to JIRA")

OP-5753 - updated foundation version

---

version.gradle

**Ticket:** [OP-5828](https://endios.atlassian.net/browse/OP-5828 "Link to JIRA")

OP-5828 - updated foundation version

---

version.gradle

**Ticket:** [OP-5776](https://endios.atlassian.net/browse/OP-5776 "Link to JIRA")

OP-5776 - updated foundation version

---

version.gradle

**Ticket:** [OP-5776](https://endios.atlassian.net/browse/OP-5776 "Link to JIRA")

OP-5776 - update foundation version

---

version.gradle

**Ticket:** [OP-5846](https://endios.atlassian.net/browse/OP-5846 "Link to JIRA")

OP-5846 - update foundation version

---

version.gradle

**Ticket:** [OP-5637](https://endios.atlassian.net/browse/OP-5637)

OP-5637 Push notifications crash on Android 12

---

version.gradle

**Ticket:** [OP-1005](https://endios.atlassian.net/browse/OP-1005)

OP-1005 [Placeholder] Android: SAP Login

---

version.gradle

**Ticket:** [OP-5418](https://endios.atlassian.net/browse/OP-5418)

OP-5418 [android] Biometric authentication during the login workflow

---

version.gradle

**Ticket:** [OP-5919](https://endios.atlassian.net/browse/OP-5919)

OP-5919 [Android][Kassel][CSS Profile Widget] Incorrect color for profile data fields

---

version.gradle

**Ticket:** [OP-5833](https://endios.atlassian.net/browse/OP-5833)

OP-5833 Android: Plauen: Report Widget: Saving Button

---

version.gradle

**Ticket:** [OP-5944](https://endios.atlassian.net/browse/OP-5944)

OP-5944 Android: Login fields are overlapped with keyboard and user is not able to view

---

version.gradle

**Ticket:** [OP-5989](https://endios.atlassian.net/browse/OP-5989 "Link to JIRA")

OP-5989 - updated foundation version

---

version.gradle

**Ticket:** [OP-5945](https://endios.atlassian.net/browse/OP-5945)

OP-5945 Android. OneTimePicker adjustment.

---

version.gradle

**Ticket:** [OP-6012](https://endios.atlassian.net/browse/OP-6012)

OP-6012 2 biometrics prompts are shown when user session has timed out

---

version.gradle

**Ticket:** [OP-6028](https://endios.atlassian.net/browse/OP-6028)

OP-6028 Login screen doesn't close after user chose not to use biometrics

---

version.gradle

**Ticket:** [OP-6058](https://endios.atlassian.net/browse/OP-6058)

OP-6058 [Android] Crashes in Crashlitics

---

version.gradle

**Ticket:** [OP-6314](https://endios.atlassian.net/browse/OP-6314)

OP-6314 Fix warnings when building the app

---

CODEOWNERS
version.gradle

**Ticket:** [OP-6356](https://endios.atlassian.net/browse/OP-6356)
**Purpose of this Pull Request:** 
- Increase foundation version
- Added CODEOWNERS file

OP-6356 [android] adjust the one list for the consumption needs

---

version.gradle

**Ticket:** [OP-6377](https://endios.atlassian.net/browse/OP-6377)

OP-6377 Add MonthYearPicker

---

version.gradle

**Ticket:** [OP-5999](https://endios.atlassian.net/browse/OP-5999)

OP-5999 Android: Coburg: Cinema Widget: TabBar not readable

---

version.gradle

**Ticket:** [OP-6534](https://endios.atlassian.net/browse/OP-6534)

OP-6534 [Android] Fix foundation component OneDialog to have header and text use dynamic color

---

version.gradle

**Ticket:** [OP-5137](https://endios.atlassian.net/browse/OP-5137)

OP-5137 [tbd][Android] Application crashed when app restarts.

---

version.gradle

**Ticket:** [OP-6576](https://endios.atlassian.net/browse/OP-6576)

OP-6576 Würzburg: Android: push notification is not opening the URL

---

version.gradle

**Ticket:** [OP-6574](https://endios.atlassian.net/browse/OP-6574 "Link to JIRA")

OP-6574 - updated foundation version

---

version.gradle

**Ticket:** [OP-6725](https://endios.atlassian.net/browse/OP-6725)

OP-6725 [Android] Add MenuOptionDelegate to foundation.

---

version.gradle

**Ticket:** [OP-6818](https://endios.atlassian.net/browse/OP-6818 "Link to JIRA")

OP-6818 - update foundation version

---

version.gradle

**Ticket:** [OP-2334](https://endios.atlassian.net/browse/OP-2334 "Link to JIRA")

OP-2334 - updated foundation version

---

version.gradle

**Ticket:** [OP-6710](https://endios.atlassian.net/browse/OP-6710 "Link to JIRA")

OP-6710 - updated foundation version

---

version.gradle

**Ticket:** [OP-6851](https://endios.atlassian.net/browse/OP-6851 "Link to JIRA")
[OP-6851]: https://endios.atlassian.net/browse/OP-6851?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-6851 - updated foundation version

---

version.gradle

**Ticket:** [OP-6889](https://endios.atlassian.net/browse/OP-6889 "Link to JIRA")
updated foundation version'
[OP-6889]: https://endios.atlassian.net/browse/OP-6889?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-6889 - updated foundation version

---

version.gradle

**Ticket:** [OP-6919](https://endios.atlassian.net/browse/OP-6919)
[OP-6919]: https://endios.atlassian.net/browse/OP-6919?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-6919 Adjust OptionMenuDelegate.

---

version.gradle

**Ticket:** [OP-6877](https://endios.atlassian.net/browse/OP-6877 "Link to JIRA")
Implement offline functionality to send information to URL when online
[OP-6877]: https://endios.atlassian.net/browse/OP-6877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-6877 - Implement offline functionality to send information to URL when online

---

version.gradle

**Ticket:** [OP-6877](https://endios.atlassian.net/browse/OP-6877 "Link to JIRA")
[OP-6877]: https://endios.atlassian.net/browse/OP-6877?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-6877 - updated foundation version

---

version.gradle

**Ticket:** [OP-6886](https://endios.atlassian.net/browse/OP-6886)
[OP-6886]: https://endios.atlassian.net/browse/OP-6886?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-6886 Fix app module in widgets

---

version.gradle

**Ticket:** [OP-7067](https://endios.atlassian.net/browse/OP-7067 "Link to JIRA")
[OP-7067]: https://endios.atlassian.net/browse/OP-7067?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-7067 - updated foundation version

---

version.gradle

**Ticket:** [OP-7190](https://endios.atlassian.net/browse/OP-7190)
[OP-7190]: https://endios.atlassian.net/browse/OP-7190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-7190 [android] I can change my consent setting

---

version.gradle

**Ticket:** [OP-7404](https://endios.atlassian.net/browse/OP-7404)
[OP-7404]: https://endios.atlassian.net/browse/OP-7404?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-7404 Update Changers widget

---

version.gradle

**Ticket:** [OP-7411](https://endios.atlassian.net/browse/OP-7411)
[OP-7411]: https://endios.atlassian.net/browse/OP-7411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-7411 [android] Enabling global control of the analytics flag

---

version.gradle

**Ticket:** [OP-6560](https://endios.atlassian.net/browse/OP-6560)
[OP-6560]: https://endios.atlassian.net/browse/OP-6560?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-6560 [Android] DetailView V3 - Framework

---

version.gradle

**Ticket:** [FTP-804](https://endios.atlassian.net/browse/FTP-804 "Link to JIRA")
[FTP-804]: https://endios.atlassian.net/browse/FTP-804?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FTP-804 - updated foundation version

---

version.gradle

**Ticket:** [OP-7898](https://endios.atlassian.net/browse/OP-7898 "Link to JIRA")
revert foundation version to 67
[OP-7898]: https://endios.atlassian.net/browse/OP-7898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-7898 - revert foundation version to 67

---

CODEOWNERS
version.gradle

**Ticket:** [OP-7758](https://endios.atlassian.net/browse/OP-7758)
[OP-7758]: https://endios.atlassian.net/browse/OP-7758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-7758 [Android][News][MeinLübeck] Article images are not displayed

---

version.gradle

**Ticket:** [OP-7760](https://endios.atlassian.net/browse/OP-7760)
[OP-7760]: https://endios.atlassian.net/browse/OP-7760?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-7760 [android] [BAED v1.0] Personal Data View

---

version.gradle

**Ticket:** [OP-7987](https://endios.atlassian.net/browse/OP-7987)
**Purpose of this Pull Request:** Kotlin version upgrades
[OP-7987]: https://endios.atlassian.net/browse/OP-7987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-7987   [Android]Events -Detail view: Calendar icon is not aligned to left

---

version.gradle

**Ticket:** [FTP-844](https://endios.atlassian.net/browse/FTP-844 "Link to JIRA")
- Update google maps utils dependency version to fix the issue related to `NoSuchMethodError` when accessing functions in `ClusterManager`
[FTP-844]: https://endios.atlassian.net/browse/FTP-844?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FTP-844: Update google maps utils dependency

---

version.gradle

**Ticket:** [TIOP-7757CKET_ID](https://endios.atlassian.net/browse/OP-7757 "Link to JIRA")

OP-7757 - updated foundation version

---

version.gradle

**Ticket:** [OP-7757](https://endios.atlassian.net/browse/OP-7757 "Link to JIRA")
[OP-7757]: https://endios.atlassian.net/browse/OP-7757?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-7757 - updated foundation

---

version.gradle

**Ticket:** [OP-7997](https://endios.atlassian.net/browse/OP-7997 "Link to JIRA")
[OP-7997]: https://endios.atlassian.net/browse/OP-7997?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-7997 - updated foundation version

---

version.gradle

**Ticket:** [OP-7993](https://endios.atlassian.net/browse/OP-7993)
[OP-7993]: https://endios.atlassian.net/browse/OP-7993?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-7993 Create FAQ Foundation Basis

---

version.gradle

**Ticket:** [OP-8012](https://endios.atlassian.net/browse/OP-8012 "Link to JIRA")
[OP-8012]: https://endios.atlassian.net/browse/OP-8012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-8012 - update foundation version

---

version.gradle

**Ticket:** [OP-4051](https://endios.atlassian.net/browse/OP-4051 "Link to JIRA")
[OP-4051]: https://endios.atlassian.net/browse/OP-4051?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-4051 - updated foundation version

---

version.gradle

**Ticket:** [OP-8153](https://endios.atlassian.net/browse/OP-8153)
**Purpose of this Pull Request:** 
- Increase foundation version
- Remove simplexml converter dependency
[OP-8153]: https://endios.atlassian.net/browse/OP-8153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-8153   Solve vulnerabilities in Android Projekt

---

version.gradle

**Ticket:** [OP-8012](https://endios.atlassian.net/browse/OP-8012 "Link to JIRA")
[OP-8012]: https://endios.atlassian.net/browse/OP-8012?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-8012 - updated foundation

---

version.gradle

**Ticket:** [OP-8260](https://endios.atlassian.net/browse/OP-8260 "Link to JIRA")
[OP-8260]: https://endios.atlassian.net/browse/OP-8260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-8260 - updated foundation

---

version.gradle

**Ticket:** [OP-8263](https://endios.atlassian.net/browse/OP-8263 "Link to JIRA")
[OP-8263]: https://endios.atlassian.net/browse/OP-8263?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-8263 - updated foundation

---

version.gradle

**Ticket:** [OP-8085 ](https://endios.atlassian.net/browse/OP-8085)

OP-8085 [android] Add marker clustering to OneMapView

---

version.gradle

**Ticket:** [OP-8463](https://endios.atlassian.net/browse/OP-8463)
[OP-8463]: https://endios.atlassian.net/browse/OP-8463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-8463 [Foundation][Android] Fix order of deeplinking menue entries

---

version.gradle

**Ticket:** [OP-8465](https://endios.atlassian.net/browse/OP-8465)
[OP-8465]: https://endios.atlassian.net/browse/OP-8465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-8465   [Foundation][Android] Add padding in deeplinking menue between entries and the new "Häufig gestellte Fragen"

---

version.gradle

**Ticket:** [OP-8464](https://endios.atlassian.net/browse/OP-8464)
[OP-8464]: https://endios.atlassian.net/browse/OP-8464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-8464 [Android] [BAED v1.0] - add closing buttons

---

.gitignore
version.gradle

**Ticket:** [OP-8325](https://endios.atlassian.net/browse/OP-8325 "Link to JIRA")
[OP-8325]: https://endios.atlassian.net/browse/OP-8325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-8325 - updated foundation

---

.gitignore
version.gradle

**Ticket:** [OP-8353](https://endios.atlassian.net/browse/OP-8353 "Link to JIRA")
[OP-8353]: https://endios.atlassian.net/browse/OP-8353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-8353 - updated foundation

---

version.gradle

**Ticket:** [OP-8505](https://endios.atlassian.net/browse/OP-8505)
[OP-8505]: https://endios.atlassian.net/browse/OP-8505?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-8505 [Foundation] FAQ Overview screen: Fix issues found during QA

---

version.gradle

**Ticket:** [OP-8523](https://endios.atlassian.net/browse/OP-8523 "Link to JIRA")
[OP-8523]: https://endios.atlassian.net/browse/OP-8523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-8523 - updated foundation

---

version.gradle

OP-7384 🟢 [android] Dynamic colors update: Buttons

---

version.gradle

**Ticket:** [OP-8544](https://endios.atlassian.net/browse/OP-8544)
[OP-8544]: https://endios.atlassian.net/browse/OP-8544?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-8544 Foundation lint check keeps crashing

---

version.gradle

**Ticket:** [OP-8587](https://endios.atlassian.net/browse/OP-8587 "Link to JIRA")
[OP-8587]: https://endios.atlassian.net/browse/OP-8587?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-8587 - updated foundation

---

version.gradle

**Ticket:** [OP-8588](https://endios.atlassian.net/browse/OP-8588)
[OP-8588]: https://endios.atlassian.net/browse/OP-8588?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-8588 [Android] Adjust Headlines of App Rating Service

---

version.gradle

**Ticket:** [OP-7717](https://endios.atlassian.net/browse/OP-7717 "Link to JIRA")
[OP-7717]: https://endios.atlassian.net/browse/OP-7717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-7717 - updated foundation

---

CODEOWNERS
lib.gradle

**Ticket:** [OP-8627](https://endios.atlassian.net/browse/OP-8627)
**Purpose of this Pull Request:** Increase Java Version
[OP-8627]: https://endios.atlassian.net/browse/OP-8627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-8627 Automate widget publishing

---

version.gradle

**Ticket:** [OP-8691](https://endios.atlassian.net/browse/OP-8691 "Link to JIRA")
[OP-8691]: https://endios.atlassian.net/browse/OP-8691?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-8691 - updated foundation

---

version.gradle

**Ticket:** [OP-8732](https://endios.atlassian.net/browse/OP-8732)
[OP-8732]: https://endios.atlassian.net/browse/OP-8732?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-8732 [GWA v2.0 P6] [android] add new event type "meta"

---

version.gradle

**Ticket:** [OP-8759](https://endios.atlassian.net/browse/OP-8759)
[OP-8759]: https://endios.atlassian.net/browse/OP-8759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-8759 [GWA v2.0 P.6] [Android] FAQs

---

version.gradle

**Ticket:** [OP-8770](https://endios.atlassian.net/browse/OP-8770)
[OP-8770]: https://endios.atlassian.net/browse/OP-8770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-8770   [GWA v2.0 P6] [Android] Search & Filters - Make Search & Filters trackable

---

version.gradle

**Ticket:** [OP-8746](https://endios.atlassian.net/browse/OP-8746)
[OP-8746]: https://endios.atlassian.net/browse/OP-8746?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-8746 [GWA v2.0 P.6] [Android] Detail View

---

version.gradle

**Ticket:** [OP-8733](https://endios.atlassian.net/browse/OP-8733)
[OP-8733]: https://endios.atlassian.net/browse/OP-8733?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-8733 [GWA v2.0 P.6] [Android] Home Screens

---

version.gradle

**Ticket:** [OP-8950](https://endios.atlassian.net/browse/OP-8950 "Link to JIRA")
- Update foundation version
[OP-8950]: https://endios.atlassian.net/browse/OP-8950?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-8950: Update foundation version

---

version.gradle

**Ticket:** [FTP-1123](https://endios.atlassian.net/browse/FTP-1123)
[FTP-1123]: https://endios.atlassian.net/browse/FTP-1123?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FTP-1123 [Android][DNT] - Call can't be triggered after login

---

version.gradle

**Ticket:** [OP-9168](https://endios.atlassian.net/browse/OP-9168)
[OP-9168]: https://endios.atlassian.net/browse/OP-9168?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-9168 Empty pages array leads to crash

---

version.gradle

**Ticket:** [OP-9389](https://endios.atlassian.net/browse/OP-9389 "Link to JIRA")
[OP-9389]: https://endios.atlassian.net/browse/OP-9389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-9389 - updated foundation

---

version.gradle

**Ticket:** [OP-9326](https://endios.atlassian.net/browse/OP-9326)
[OP-9326]: https://endios.atlassian.net/browse/OP-9326?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-9326 [Android] [Foundation] App crashes if AppConfigContainer is null

---

version.gradle

**Ticket:** [OP-9418](https://endios.atlassian.net/browse/OP-9418)
[OP-9418]: https://endios.atlassian.net/browse/OP-9418?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-9418 [Foundation] lateinit variables not set in DetailDetailsModel

---

version.gradle

**Ticket:** [OP-9247](https://endios.atlassian.net/browse/OP-9247 "Link to JIRA")
pdated foundation
[OP-9247]: https://endios.atlassian.net/browse/OP-9247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-9247 - updated foundation

---

version.gradle

**Ticket:** [OP-9429](https://endios.atlassian.net/browse/OP-9429 "Link to JIRA")
[OP-9429]: https://endios.atlassian.net/browse/OP-9429?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-9429 - updated foundation

---

version.gradle

**Ticket:** [OP-9328](https://endios.atlassian.net/browse/OP-9328 "Link to JIRA")
1.0 [Android] Profile Widget Core Extension: Account Deletion Button on Profile Overview
[OP-9328]: https://endios.atlassian.net/browse/OP-9328?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-9328 - 1.0 [Android] Profile Widget Core Extension: Account Deletion Button on Profile Overview

---

lib_ui_tests.gradle
version.gradle

**Ticket:** [OP-9329](https://endios.atlassian.net/browse/OP-9329 "Link to JIRA")
Account Deletion - Account Deletion Confirmation Screen.
[OP-9329]: https://endios.atlassian.net/browse/OP-9329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-9329 - Account Deletion - Account Deletion Confirmation Screen #396

---

version.gradle

**Ticket:** [OP-9330](https://endios.atlassian.net/browse/OP-9330 "Link to JIRA")
Account Deletion - "Account Deletion Completed" Screen
[OP-9330]: https://endios.atlassian.net/browse/OP-9330?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-9330 - Account Deletion - "Account Deletion Completed" Screen

---

version.gradle

**Ticket:** [OP- 9331](https://endios.atlassian.net/browse/OP- 9331 "Link to JIRA")

OP- 9331 - updated foundation

---

version.gradle

**Ticket:** [OP-9096](https://endios.atlassian.net/browse/OP-9096 "Link to JIRA")
[OP-9096]: https://endios.atlassian.net/browse/OP-9096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-9096 - updated foundation

---

version.gradle

**Ticket:** [OP-8763](https://endios.atlassian.net/browse/OP-8763)
[OP-8763]: https://endios.atlassian.net/browse/OP-8763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-8763 [GWA v2.0 P.6] [Android] Video Widget

---

version.gradle

**Ticket:** [OP-8959](https://endios.atlassian.net/browse/OP-8959 "Link to JIRA")
[OP-8959]: https://endios.atlassian.net/browse/OP-8959?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-8959 - updated foundation

---

version.gradle

**Ticket:** [PMPO-5091](https://endios.atlassian.net/browse/PMPO-5091)
[PMPO-5091]: https://endios.atlassian.net/browse/PMPO-5091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

PMPO-5091 [Android] minimize app loading time

---

version.gradle

**Ticket:** [OP-8943](https://endios.atlassian.net/browse/OP-8943)
- Remove epoxy library
- Increase foundation version
[OP-8943]: https://endios.atlassian.net/browse/OP-8943?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-8943 Remove usage of Epoxy library

---

version.gradle

**Ticket:** [OP-8948](https://endios.atlassian.net/browse/OP-8948 "Link to JIRA")
[OP-8948]: https://endios.atlassian.net/browse/OP-8948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-8948 - updated foundation

---

version.gradle

**Ticket:** [OP-8582](https://endios.atlassian.net/browse/OP-8582)
[OP-8582]: https://endios.atlassian.net/browse/OP-8582?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-8582 [Android] Dynamic colors update: Tiles

---

version.gradle

**Purpose of this Pull Request:** Finish 24.01 release

OP-1 Finish 24.01 release

---

version.gradle

**Ticket:** [OP-9778](https://endios.atlassian.net/browse/OP-9778 "Link to JIRA")
[OP-9778]: https://endios.atlassian.net/browse/OP-9778?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-9778 - [ITC-REG] Changes to Profile Widget

---

version.gradle

**Ticket:** [OP-9772](https://endios.atlassian.net/browse/OP-9772 "Link to JIRA")
[OP-9772]: https://endios.atlassian.net/browse/OP-9772?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-9772 - updated foundation

---

version.gradle

**Ticket:** [OP-10000](https://endios.atlassian.net/browse/OP-10000 "Link to JIRA")
[OP-10000]: https://endios.atlassian.net/browse/OP-10000?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-10000 - updated foundation

---

version.gradle

**Ticket:** [OP-10013](https://endios.atlassian.net/browse/OP-10013 "Link to JIRA")
[OP-10013]: https://endios.atlassian.net/browse/OP-10013?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-10013 - updated foundation

---

version.gradle

**Ticket:** [OP-10030](https://endios.atlassian.net/browse/OP-10030 "Link to JIRA")
[OP-10030]: https://endios.atlassian.net/browse/OP-10030?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-10030 - updated foundation

---

version.gradle

**Ticket:** [OP-9888](https://endios.atlassian.net/browse/OP-9888)
[OP-9888]: https://endios.atlassian.net/browse/OP-9888?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-9888 [Android] [ITC-PWR] - Password Reset for ITC

---

version.gradle

**Ticket:** [OP-8734](https://endios.atlassian.net/browse/OP-8734)
[OP-8734]: https://endios.atlassian.net/browse/OP-8734?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-8734 [GWA v2.0 P.6] [Android] Login, Registration, Account Deletion

---

version.gradle

**Ticket:** [OP-10015](https://endios.atlassian.net/browse/OP-10015 "Link to JIRA")
[OP-10015]: https://endios.atlassian.net/browse/OP-10015?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-10015 - updated foundation

---

version.gradle

**Ticket:** [OP-10068](https://endios.atlassian.net/browse/OP-10068)
[OP-10068]: https://endios.atlassian.net/browse/OP-10068?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-10068 [android] changes to password recovery workflow v2

---

version.gradle

**Ticket:** [OP-9279](https://endios.atlassian.net/browse/OP-9279 "Link to JIRA")
[OP-9279]: https://endios.atlassian.net/browse/OP-9279?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-9279 - updated foundation

---

version.gradle

**Ticket:** [OP-8762](https://endios.atlassian.net/browse/OP-8762)
[OP-8762]: https://endios.atlassian.net/browse/OP-8762?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-8762 [GWA v2.0 P.6] [Android] PDF Widget

---

version.gradle

**Ticket:** [OP-10080](https://endios.atlassian.net/browse/OP-10080 "Link to JIRA")
[OP-10080]: https://endios.atlassian.net/browse/OP-10080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-10080 - updated foundation

---

version.gradle

**Ticket:** [OP-9739](https://endios.atlassian.net/browse/OP-9739)
[OP-9739]: https://endios.atlassian.net/browse/OP-9739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-9739 [Android] Prevent Overlays from being dismissed/skipped

---

version.gradle

**Ticket:** [OP-10101](https://endios.atlassian.net/browse/OP-10101)
[OP-10101]: https://endios.atlassian.net/browse/OP-10101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-10101 Don't show error message if getting user data fails after login

---

version.gradle

**Ticket:** [OP-9669](https://endios.atlassian.net/browse/OP-9669)
[OP-9669]: https://endios.atlassian.net/browse/OP-9669?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-9669 [Android] [REG] - Option for Pre-Filled Registration Fields

---

version.gradle

**Ticket:** [OP-10329](https://endios.atlassian.net/browse/OP-10329)
[OP-10329]: https://endios.atlassian.net/browse/OP-10329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-10329 Android: Kassel: text is not shown in overlays

---

version.gradle

**Ticket:** [OP-10338](https://endios.atlassian.net/browse/OP-10338)
[OP-10338]: https://endios.atlassian.net/browse/OP-10338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-10338 [Android][Foundation] Adjust Dynamic Colouring Outputs

---

version.gradle

**Ticket:** [OP-10571](https://endios.atlassian.net/browse/OP-10571)
[OP-10571]: https://endios.atlassian.net/browse/OP-10571?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-10571 [Android] DynCol v1.1: Test CSS Widgets

---

version.gradle

**Ticket:** [OP-10555](https://endios.atlassian.net/browse/OP-10555)
[OP-10555]: https://endios.atlassian.net/browse/OP-10555?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-10555 [android] review how we open the webview

---

version.gradle

**Ticket:** [OP-10948](https://endios.atlassian.net/browse/OP-10948)
[OP-10948]: https://endios.atlassian.net/browse/OP-10948?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-10948 [Android] DynCol v1.1: Test CSS Widgets

---

version.gradle

**Ticket:** [OP-9739](https://endios.atlassian.net/browse/OP-9739 "Link to JIRA")
[Android] Prevent Overlays from being dismissed/skipped
[OP-9739]: https://endios.atlassian.net/browse/OP-9739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-9739 - [Android] Prevent Overlays from being dismissed/skipped

---

version.gradle

**Ticket:** [OP-10953](https://endios.atlassian.net/browse/OP-10953)
[OP-10953]: https://endios.atlassian.net/browse/OP-10953?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-10953 [Android] Implement CSS Account Check

---

version.gradle

**Ticket:** [OP-10882](https://endios.atlassian.net/browse/OP-10882 "Link to JIRA")
updated foundation 
[OP-10882]: https://endios.atlassian.net/browse/OP-10882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-10882 - [Android][Bäder Suite][Kassel]: Displays HTML code in ticket descriptions

---

version.gradle

**Ticket:** [FTP-1247](https://endios.atlassian.net/browse/FTP-1247)
[FTP-1247]: https://endios.atlassian.net/browse/FTP-1247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

FTP-1247 one_widget_echarging (Mobilität)

---

version.gradle

**Ticket:** [OP-9287](https://endios.atlassian.net/browse/OP-9287 "Link to JIRA")
[OP-9287]: https://endios.atlassian.net/browse/OP-9287?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-9287 - updated foundation

---

version.gradle

**Ticket:** [OP-11145](https://endios.atlassian.net/browse/OP-11145 "Link to JIRA")
[Android] Registration possible without agreeing to data policy
[OP-11145]: https://endios.atlassian.net/browse/OP-11145?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-11145 - [Android] Registration possible without agreeing to data policy

---

version.gradle

**Ticket:** [OP-11243](https://endios.atlassian.net/browse/OP-11243 "Link to JIRA")
[OP-11243]: https://endios.atlassian.net/browse/OP-11243?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-11243 - updated foundation

---

version.gradle

**Ticket:** [OP-11166](https://endios.atlassian.net/browse/OP-11166)
[OP-11166]: https://endios.atlassian.net/browse/OP-11166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-11166 [android] Price Screen

---

version.gradle

**Ticket:** [OP-11261](https://endios.atlassian.net/browse/OP-11261 "Link to JIRA")
[OP-11261]: https://endios.atlassian.net/browse/OP-11261?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-11261 - updated foundation

---

version.gradle

**Ticket:** [OP-11347](https://endios.atlassian.net/browse/OP-11347 "Link to JIRA")
[OP-11347]: https://endios.atlassian.net/browse/OP-11347?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-11347 - updated foundation

---

version.gradle

**Ticket:** [OP-11389](https://endios.atlassian.net/browse/OP-11389)
[OP-11389]: https://endios.atlassian.net/browse/OP-11389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-11389 UI changes Testing

---

version.gradle

**Ticket:** [OP-11179](https://endios.atlassian.net/browse/OP-11179)
[OP-11179]: https://endios.atlassian.net/browse/OP-11179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-11179 [android] Optimization Screen

---

version.gradle

**Ticket:** [OP-11468](https://endios.atlassian.net/browse/OP-11468 "Link to JIRA")
remove getSecondaryColor() from composeUtils.kt
[OP-11468]: https://endios.atlassian.net/browse/OP-11468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-11468 - remove getSecondaryColor() from composeUtils.kt

---

version.gradle

**Ticket:** [OP-11181](https://endios.atlassian.net/browse/OP-11181)
[OP-11181]: https://endios.atlassian.net/browse/OP-11181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-11181 [android] Cost Screen

---

version.gradle

**Ticket:** [OP-11411](https://endios.atlassian.net/browse/OP-11411 "Link to JIRA")
[OP-11411]: https://endios.atlassian.net/browse/OP-11411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-11411 - updated foundation

---

version.gradle

**Ticket:** [OP-11471](https://endios.atlassian.net/browse/OP-11471 "Link to JIRA")
[OP-11471]: https://endios.atlassian.net/browse/OP-11471?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-11471 - updated foundation

---

version.gradle

**Ticket:** [OP-11491](https://endios.atlassian.net/browse/OP-11491)
**Purpose of this Pull Request:** Increased foundation version
[OP-11491]: https://endios.atlassian.net/browse/OP-11491?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-11491 Android /Consumption- Business logic testing

---

version.gradle

**Ticket:** [OP-11599](https://endios.atlassian.net/browse/OP-11599 "Link to JIRA")
[OP-11599]: https://endios.atlassian.net/browse/OP-11599?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-11599 - updated foundation

---

version.gradle

**Ticket:** [OP-11600](https://endios.atlassian.net/browse/OP-11600 "Link to JIRA")
[OP-11600]: https://endios.atlassian.net/browse/OP-11600?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-11600 - updated foundation

---

version.gradle

**Ticket:** [OP-11312](https://endios.atlassian.net/browse/OP-11312 "Link to JIRA")
[OP-11312]: https://endios.atlassian.net/browse/OP-11312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-11312 - updated foundation

---

version.gradle

**Ticket:** [OP-11629](https://endios.atlassian.net/browse/OP-11629)
[OP-11629]: https://endios.atlassian.net/browse/OP-11629?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-11629 Android /Consumption- Business logic testing - Part2

---

version.gradle

**Ticket:** [OP-11659](https://endios.atlassian.net/browse/OP-11659 "Link to JIRA")
[OP-11659]: https://endios.atlassian.net/browse/OP-11659?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-11659 - updated foundation

---

version.gradle

**Ticket:** [OP-11539](https://endios.atlassian.net/browse/OP-11539 "Link to JIRA")
[OP-11539]: https://endios.atlassian.net/browse/OP-11539?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-11539 - updated foundation

---

version.gradle

**Ticket:** [OP-11784](https://endios.atlassian.net/browse/OP-11784)
**Purpose of this Pull Request:** Upgrading android gradle plugin
[OP-11784]: https://endios.atlassian.net/browse/OP-11784?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-11784 FTP server needs latest gradle version for publishing

---

version.gradle

**Ticket:** [OP-11773](https://endios.atlassian.net/browse/OP-11773 "Link to JIRA")
[OP-11773]: https://endios.atlassian.net/browse/OP-11773?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-11773 - updated foundation

---

version.gradle

**Ticket:** [OP-11855](https://endios.atlassian.net/browse/OP-11855 "Link to JIRA")
updating kotlin and compose compiler versions
[OP-11855]: https://endios.atlassian.net/browse/OP-11855?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-11855 - updating kotlin and compose compiler versions

---

version.gradle

**Ticket:** [OP-10892](https://endios.atlassian.net/browse/OP-10892 "Link to JIRA")
fixed kotlin coroutine version
[OP-10892]: https://endios.atlassian.net/browse/OP-10892?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-10892 - fixed kotlin coroutine version

---

version.gradle

**Ticket:** [OP-5610](https://endios.atlassian.net/browse/OP-5610 "Link to JIRA")
added koin for compose
[OP-5610]: https://endios.atlassian.net/browse/OP-5610?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-5610 - added koin for compose

---

version.gradle

**Ticket:** [OP-12107](https://endios.atlassian.net/browse/OP-12107 "Link to JIRA")
[Android][Foundation][ACC-DEL] ALL: error screen appears after profile deletion - unable to access app
[OP-12107]: https://endios.atlassian.net/browse/OP-12107?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-12107 - [Android][Foundation][ACC-DEL] ALL: error screen appears after profile deletion - unable to access app

---

version.gradle

**Ticket:** [OP-12247](https://endios.atlassian.net/browse/OP-12247)
[OP-12247]: https://endios.atlassian.net/browse/OP-12247?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-12247 [Android] Available Month not selectable in the date picker

---

version.gradle

**Ticket:** [OP-12258](https://endios.atlassian.net/browse/OP-12258)
[OP-12258]: https://endios.atlassian.net/browse/OP-12258?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-12258 [Android] Toolbar crashes if title is null

---

version.gradle

OP-12304 [Android] Optional colors in DYNT-Widget

---

version.gradle

**Ticket:** [OP-12389](https://endios.atlassian.net/browse/OP-12389)
[OP-12389]: https://endios.atlassian.net/browse/OP-12389?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-12389 [Android][Foundation][MONTANA][Contract] Document is not shown

---

version.gradle

**Ticket:** [OP-12153](https://endios.atlassian.net/browse/OP-12153)
[OP-12153]: https://endios.atlassian.net/browse/OP-12153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-12153   [Android] Foundation is running out of memory

---

version.gradle

**Ticket:** [OP-12388](https://endios.atlassian.net/browse/OP-12388)
**Purpose of this Pull Request:** Fix a bug in the test library
[OP-12388]: https://endios.atlassian.net/browse/OP-12388?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-12388 [Android] Show tabs based on selected contract

---

version.gradle

**Ticket:** [OP-12349](https://endios.atlassian.net/browse/OP-12349)
[OP-12349]: https://endios.atlassian.net/browse/OP-12349?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-12349 [Android] Add month-, and week-, and day-view to Cost Tab

---

version.gradle

**Ticket:** [OP-12559](https://endios.atlassian.net/browse/OP-12559 "Link to JIRA")
[OP-12559]: https://endios.atlassian.net/browse/OP-12559?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-12559 - updated foundation version

---

version.gradle

**Ticket:** [OP-12561](https://endios.atlassian.net/browse/OP-12561 "Link to JIRA")
[OP-12561]: https://endios.atlassian.net/browse/OP-12561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-12561 - updated foundation

---

version.gradle

**Ticket:** [OP-12562](https://endios.atlassian.net/browse/OP-12562 "Link to JIRA")
[OP-12562]: https://endios.atlassian.net/browse/OP-12562?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-12562 - updated foundation

---

version.gradle

**Ticket:** [OP-11821](https://endios.atlassian.net/browse/OP-11821 "Link to JIRA")
[OP-11821]: https://endios.atlassian.net/browse/OP-11821?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-11821 - updated foundation

---

version.gradle

**Ticket:** [OP-12563](https://endios.atlassian.net/browse/OP-12563 "Link to JIRA")
[OP-12563]: https://endios.atlassian.net/browse/OP-12563?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-12563 - updated foundation

---

version.gradle

**Ticket:** [OP-12530](https://endios.atlassian.net/browse/OP-12530 "Link to JIRA")
[OP-12530]: https://endios.atlassian.net/browse/OP-12530?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-12530 - updated foundation

---

version.gradle

**Ticket:** [OP-12756](https://endios.atlassian.net/browse/OP-12756)
- Increase foundation version
- Add auth version 
[OP-12756]: https://endios.atlassian.net/browse/OP-12756?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-12756 [Android][Neustrelitz]Login: The login screen uses the wrong font for the username and password input fields

---

version.gradle

**Ticket:** [OP-12753](https://endios.atlassian.net/browse/OP-12753)
**Purpose of this Pull Request:** Increase auth module version
[OP-12753]: https://endios.atlassian.net/browse/OP-12753?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-12753 [ITC-REG v1.1][Android] Mobile Development

---

version.gradle

**Ticket:** [OP-12561](https://endios.atlassian.net/browse/OP-12561 "Link to JIRA")
[Android] [BFH 2025] [VO/TB] [Detail View] Contact Box
[OP-12561]: https://endios.atlassian.net/browse/OP-12561?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-12561 - [Android] [BFH 2025] [VO/TB] [Detail View] Contact Box

---

version.gradle

**Ticket:** [OP-12770](https://endios.atlassian.net/browse/OP-12770 "Link to JIRA")
[Android][BFH 2025][VO/TB] One List Large
[OP-12770]: https://endios.atlassian.net/browse/OP-12770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-12770 - [Android][BFH 2025][VO/TB] One List Large

---

version.gradle

**Ticket:** [OP-12777](https://endios.atlassian.net/browse/OP-12777 "Link to JIRA")
[android] store and handle isErp flag lifecycle locally
[OP-12777]: https://endios.atlassian.net/browse/OP-12777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-12777 - [android] store and handle isErp flag lifecycle locally

---

version.gradle

**Ticket:** [OP-12777](https://endios.atlassian.net/browse/OP-12777 "Link to JIRA")
fixing botched publishing of version 5.0.17.
there is no need to publish this version once merged
[OP-12777]: https://endios.atlassian.net/browse/OP-12777?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-12777 - updated foundation

---

version.gradle

**Ticket:** [OP-12770](https://endios.atlassian.net/browse/OP-12770 "Link to JIRA")
[OP-12770]: https://endios.atlassian.net/browse/OP-12770?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-12770 - updated foundation

---

version.gradle

**Ticket:** [OP-12770 ](https://endios.atlassian.net/browse/OP-12770 )

OP-12770 [Android][BFH 2025][VO/TB] One List Large

---

version.gradle

**Ticket:** [OP-12934](https://endios.atlassian.net/browse/OP-12934)
[OP-12934]: https://endios.atlassian.net/browse/OP-12934?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-12934 [Android] [BFH 2025] [VO/TB] [Controls] Select (Context Switch)

---

version.gradle

**Ticket:** [OP-13094](https://endios.atlassian.net/browse/OP-13094)
[OP-13094]: https://endios.atlassian.net/browse/OP-13094?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-13094 [Android] [BFH 2025] [VO/TB] [Tiles] Basic

---

version.gradle

**Ticket:** [AGENCY-5973](https://endios.atlassian.net/browse/AGENCY-5973 "Link to JIRA")
[AGENCY-5973]: https://endios.atlassian.net/browse/AGENCY-5973?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

AGENCY-5973 - updated foundation

---

version.gradle

**Ticket:** [OP-13121](https://endios.atlassian.net/browse/OP-13121 "Link to JIRA")
[OP-13121]: https://endios.atlassian.net/browse/OP-13121?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-13121 - updated foundation

---

version.gradle

**Ticket:** [OP-13095](https://endios.atlassian.net/browse/OP-13095)
[OP-13095]: https://endios.atlassian.net/browse/OP-13095?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-13095 [Android] [BFH 2025] [VO/TB] [Tiles] Basic Image

---

version.gradle

**Ticket:** [OP-13195](https://endios.atlassian.net/browse/OP-13195 "Link to JIRA")
[OP-13195]: https://endios.atlassian.net/browse/OP-13195?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-13195 - updated foundation

---

version.gradle

**Ticket:** [OP-13292](https://endios.atlassian.net/browse/OP-13292)
[OP-13292]: https://endios.atlassian.net/browse/OP-13292?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-13292 [Android] Provide menu resources from foundation

---

version.gradle

**Ticket:** [OP-13091](https://endios.atlassian.net/browse/OP-13091 "Link to JIRA")
[OP-13091]: https://endios.atlassian.net/browse/OP-13091?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-13091 - updated foundation

---

version.gradle

**Ticket:** [OP-13329](https://endios.atlassian.net/browse/OP-13329)
[OP-13329]: https://endios.atlassian.net/browse/OP-13329?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-13329 [Android] [BFH 2025] [VO/TB] [Tiles] Gallery

---

version.gradle

**Ticket:** [OP-13351](https://endios.atlassian.net/browse/OP-13351)
[OP-13351]: https://endios.atlassian.net/browse/OP-13351?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-13351 [Android] [BFH 2025] [VO/TB] [Tiles] Dynamic

---

version.gradle

**Ticket:** [OP-13436](https://endios.atlassian.net/browse/OP-13436)
[OP-13436]: https://endios.atlassian.net/browse/OP-13436?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-13436 [Android] Tiles need double tap in order to be clicked

---

version.gradle

**Ticket:** [OP-13353](https://endios.atlassian.net/browse/OP-13353)
[OP-13353]: https://endios.atlassian.net/browse/OP-13353?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-13353 [Android] [BFH 2025] [VO/TB] [Tiles] Slider

---

version.gradle

**Ticket:** [OP-13422](https://endios.atlassian.net/browse/OP-13422)
[OP-13422]: https://endios.atlassian.net/browse/OP-13422?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-13422 [Android] [BFH 2025] [VO/TB] Bottom Sheets

---

version.gradle

**Ticket:** [OP-13598](https://endios.atlassian.net/browse/OP-13598)
[OP-13598]: https://endios.atlassian.net/browse/OP-13598?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-13598 [android]Reporting push usage to backend

---

version.gradle

OP-12934 - updated foundation

---

version.gradle

**Ticket:** [OP-13463](https://endios.atlassian.net/browse/OP-13463 "Link to JIRA")
[Android] Adjust Color of Navigation/App Bar Elements
[OP-13463]: https://endios.atlassian.net/browse/OP-13463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-13463 - [Android] Adjust Color of Navigation/App Bar Elements

---

version.gradle

**Ticket:** [OP-13367](https://endios.atlassian.net/browse/OP-13367 "Link to JIRA")
[OP-13367]: https://endios.atlassian.net/browse/OP-13367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-13367 - updated foundation

---

version.gradle

**Ticket:** [OP-13717](https://endios.atlassian.net/browse/OP-13717)
[OP-13717]: https://endios.atlassian.net/browse/OP-13717?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-13717 [Android] NavBar title cannot be set

---

version.gradle

**Ticket:** [OP-12205](https://endios.atlassian.net/browse/OP-12205)
[OP-12205]: https://endios.atlassian.net/browse/OP-12205?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-12205 [Android][BFH][Registration] Missing Role for Headlines

---

version.gradle

**Ticket:** [OP-13737](https://endios.atlassian.net/browse/OP-13737 "Link to JIRA")
[Android][Foundation] Use Native Date Picker when using TalkBack
[OP-13737]: https://endios.atlassian.net/browse/OP-13737?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-13737 - [Android][Foundation] Use Native Date Picker when using TalkBack

---

version.gradle

**Ticket:** [OP-13380](https://endios.atlassian.net/browse/OP-13380)
[OP-13380]: https://endios.atlassian.net/browse/OP-13380?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-13380 [Android][BFH 2025][VO/TB] Data Visualization (Charts)

---

version.gradle

**Ticket:** [OP-13883](https://endios.atlassian.net/browse/OP-13883 "Link to JIRA")
[OP-13883]: https://endios.atlassian.net/browse/OP-13883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-13883 - updated foundation

---

version.gradle

**Ticket:** [OP-13614](https://endios.atlassian.net/browse/OP-13614)
[OP-13614]: https://endios.atlassian.net/browse/OP-13614?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-13614 [SALESFORCE] Enable MarketingCloud analytics

---

version.gradle

**Ticket:** [OP-13367](https://endios.atlassian.net/browse/OP-13367 "Link to JIRA")
[OP-13883](https://endios.atlassian.net/browse/OP-13883) - [Android][BFH][VO/TB][Content] Detail View: Opening Hours Box
[OP-13367](https://endios.atlassian.net/browse/OP-13367) - [Android][BFH 2025][VO/TB][Overlays] Overlay is not automatically focused
[OP-13367]: https://endios.atlassian.net/browse/OP-13367?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OP-13883]: https://endios.atlassian.net/browse/OP-13883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[OP-13367]: https://endios.atlassian.net/browse/OP-13367?atlOrigin=eyJpIjoiNWRkN …

OP-13367/OP-13883 - Overlay is not automatically focused/View: Opening Hours Box

---

version.gradle

**Ticket:** [OP-13882](https://endios.atlassian.net/browse/OP-13882 "Link to JIRA")
[OP-13882]: https://endios.atlassian.net/browse/OP-13882?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-13882 - updated foundation

---

version.gradle

**Ticket:** [OP-13883](https://endios.atlassian.net/browse/OP-13883 "Link to JIRA")
[Android][BFH][VO/TB][Content] Detail View: Opening Hours Box
[OP-13883]: https://endios.atlassian.net/browse/OP-13883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-13883 - [Android][BFH][VO/TB][Content] Detail View: Opening Hours Box

---

version.gradle

**Ticket:** [OP-13741](https://endios.atlassian.net/browse/OP-13741)
**Purpose of this Pull Request:** Upgrade target SDK to API 35
[OP-13741]: https://endios.atlassian.net/browse/OP-13741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-13741 [Android] Upgrade target SDK to API 35

---

tooling/.detekt/detekt.gradle

**Purpose of this Pull Request:** Fix failing github actions for publishing

Upgrade detekt version

---

tooling/.ktlint/ktlint.gradle

Fix ktlint task

---

version.gradle

**Ticket:** [OP-13829](https://endios.atlassian.net/browse/OP-13829)
**Purpose of this Pull Request:** Increase auth version
[OP-13829]: https://endios.atlassian.net/browse/OP-13829?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-13829 [Android] [BFH 2025] [TM] Text Input Fields

---

version.gradle

**Ticket:** [OP-14155](https://endios.atlassian.net/browse/OP-14155)
[OP-14155]: https://endios.atlassian.net/browse/OP-14155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-14155 [Android] Implement in-app URL handling from push notifications

---

version.gradle

**Ticket:** [OP-14282](https://endios.atlassian.net/browse/OP-14282)
[OP-14282]: https://endios.atlassian.net/browse/OP-14282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-14282 [android] Register marketing cloud contacts with contact ID

---

CODEOWNERS
version.gradle

**Ticket:** [OP-14135](https://endios.atlassian.net/browse/OP-14135 "Link to JIRA")
[OP-14135]: https://endios.atlassian.net/browse/OP-14135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

OP-14135 - updated foundation
